# Generated by Django 5.0.1 on 2024-04-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediacategory_rename_commet_member_comment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_suggestion',
            field=models.BooleanField(default=False),
        ),
    ]
