# Generated by Django 5.0.1 on 2024-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reportcategory_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
