# Generated by Django 5.0.1 on 2024-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
    ]
