# Generated by Django 5.0.1 on 2024-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_question_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
