# Generated by Django 5.0.7 on 2024-10-15 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_districta_districte_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('beneficiary', models.TextField(blank=True, null=True)),
                ('statue', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100)),
                ('type', models.CharField(choices=[('Community', 'Community'), ('Women', 'Women'), ('Youth', 'Youth')], max_length=100)),
                ('lrd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
